/**
 * Code generator: ConvographConfig → TypeScript source.
 *
 * Produces a single .ts file with:
 *   - A `Topic` union of all topic names declared in agent.yaml
 *   - One interface per topic (e.g. `FlightBookingSlots`) with each
 *     slot typed according to its declared `type`. Slots marked
 *     `required: true` are non-optional; everything else is optional.
 *   - A `TopicToSlots` mapping for type-level lookups
 *
 * Notes:
 *   - Pure function — takes a config, returns a string. Easy to unit
 *     test and to call from anywhere (CLI, dev server, npm script).
 *   - Output is deterministic; same input → byte-identical output. Safe
 *     to diff in PRs.
 */

import type { ConvographConfig, Slot } from "../core/config";

/* ──────────────────────────────────────────────────────────────────────── */
/* Helpers                                                                   */
/* ──────────────────────────────────────────────────────────────────────── */

/** snake_case → PascalCase. e.g. "flight_booking" → "FlightBooking". */
function pascalCase(s: string): string {
  return s
    .split(/[_-]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Maps a YAML slot type to a TypeScript type expression. */
function slotTypeToTs(slot: Slot): string {
  switch (slot.type) {
    case "enum":
      // Always a string literal union
      return slot.values!.map((v) => JSON.stringify(v)).join(" | ");
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
    case "date":
    case "time":
    case "datetime":
    case "email":
    case "phone":
    case "url":
      return "string";
  }
}

/** Render a JSDoc comment for a slot, or return "" if there's nothing to say. */
function slotDoc(slot: Slot, indent: string): string {
  const lines: string[] = [];
  if (slot.description) lines.push(slot.description);
  const constraints: string[] = [];
  if (slot.min !== undefined) constraints.push(`min: ${slot.min}`);
  if (slot.max !== undefined) constraints.push(`max: ${slot.max}`);
  if (slot.max_length !== undefined)
    constraints.push(`max length: ${slot.max_length}`);
  if (slot.default !== undefined)
    constraints.push(`default: ${JSON.stringify(slot.default)}`);
  if (constraints.length > 0) lines.push(`(${constraints.join(", ")})`);
  if (lines.length === 0) return "";
  return (
    `${indent}/**\n` +
    lines.map((l) => `${indent} * ${l}`).join("\n") +
    `\n${indent} */\n`
  );
}

/* ──────────────────────────────────────────────────────────────────────── */
/* Main entry                                                                */
/* ──────────────────────────────────────────────────────────────────────── */

const HEADER = `// =============================================================================
// AUTO-GENERATED by convograph codegen — DO NOT EDIT
// Run \`npm run codegen\` to regenerate from agent.yaml.
// =============================================================================
`;

export interface GenerateTypesOptions {
  /**
   * If set, included in the file header for traceability.
   */
  sourceFile?: string;
}

export function generateTypes(
  cfg: ConvographConfig,
  opts: GenerateTypesOptions = {}
): string {
  const out: string[] = [];

  out.push(HEADER);
  out.push(`// Project: ${cfg.name} (v${cfg.version})`);
  if (opts.sourceFile) out.push(`// Source:  ${opts.sourceFile}`);
  out.push(`// Topics:  ${cfg.topics.length}`);
  out.push("");

  /* ─── Topic union ─────────────────────────────────────────────────── */
  out.push("/** All task-topic ids declared in agent.yaml. */");
  if (cfg.topics.length === 1) {
    out.push(`export type Topic = ${JSON.stringify(cfg.topics[0].name)};`);
  } else {
    out.push("export type Topic =");
    cfg.topics.forEach((t, i) => {
      const last = i === cfg.topics.length - 1;
      out.push(`  | ${JSON.stringify(t.name)}${last ? ";" : ""}`);
    });
  }
  out.push("");
  out.push(
    `export const TOPICS = [${cfg.topics
      .map((t) => JSON.stringify(t.name))
      .join(", ")}] as const;`
  );
  out.push("");

  /* ─── Per-topic slot interfaces ───────────────────────────────────── */
  for (const topic of cfg.topics) {
    const ifaceName = `${pascalCase(topic.name)}Slots`;
    out.push(`/**`);
    out.push(` * Slot record for the "${topic.name}" topic.`);
    if (topic.description) out.push(` * ${topic.description}`);
    out.push(` */`);
    out.push(`export interface ${ifaceName} {`);
    for (const slot of topic.slots) {
      const optional = !slot.required ? "?" : "";
      const tsType = slotTypeToTs(slot);
      const doc = slotDoc(slot, "  ");
      out.push(`${doc}  ${slot.name}${optional}: ${tsType};`);
    }
    out.push(`}`);
    out.push("");
  }

  /* ─── Topic → Slots mapping ───────────────────────────────────────── */
  out.push("/** Type-level lookup of slots by topic id. */");
  out.push("export interface TopicToSlots {");
  for (const topic of cfg.topics) {
    const ifaceName = `${pascalCase(topic.name)}Slots`;
    out.push(`  ${JSON.stringify(topic.name)}: ${ifaceName};`);
  }
  out.push("}");
  out.push("");

  /* ─── Combined slots union ────────────────────────────────────────── */
  out.push(
    "/** Union of all topic slot types — useful when storing a draft of any topic. */"
  );
  if (cfg.topics.length === 1) {
    out.push(
      `export type AnyTopicSlots = ${pascalCase(cfg.topics[0].name)}Slots;`
    );
  } else {
    out.push("export type AnyTopicSlots =");
    cfg.topics.forEach((t, i) => {
      const last = i === cfg.topics.length - 1;
      out.push(`  | ${pascalCase(t.name)}Slots${last ? ";" : ""}`);
    });
  }
  out.push("");

  return out.join("\n");
}
